### ISSUE TITLE
Tracking: Loosen Key Package Upload Validation

### ISSUE THREAD

**Issue by neekolas** [xmtp/xmtp-node-go#399]
The goal of this project is to allow clients to upload key packages _before_ publishing identity updates. While we are rolling out these changes, we can do a bit of cleanup of some of the legacy APIs that predate the identity work.

## Phase 1
```[tasklist]
- [ ] Change logic in `RegisterInstallation` and `UploadKeyPackage` to not validate that the key package is part of a given inbox. Instead it should just validate the signatures and extract the installation ID.
- [ ] Update database schema to not store the `inbox_id` on installations, since we don't have that trusted information. Also remove the expiration field
- [ ] Update client to call `UploadKeyPackage` _before_ publishing an identity update adding the installation
- [ ] Make the `ValidateKeyPackages` endpoint in the validation service stop checking the lifetime of key packages, since that check will panic if the lifetime is not set
- [ ] Stop setting a lifetime on new key packages. This will prevent them from expiring
- [ ] Remove `RegisterInstallation`, `RevokeInstallation` and `GetIdentityUpdates` APIs from the libxmtp traits
```

## Phase 2

```[tasklist]
- [ ] Roll out changes from phase 1 to all clients
- [ ] In the `PublishIdentityUpdate` flow, check to make sure the installation is already registered. Reject any identity updates that reference an installation that does not have a key package stored in the DB.
- [ ] Remove `RevokeInstallation` and `GetIdentityUpdates` from the protos and server
```

## Phase 3

```[tasklist]
- [ ] Completely remove `RegisterInstallation` endpoint.
- [ ] Remove `ValidateV3KeyPackages` from the `MlsValidate` service. 
- [ ] Remove any handling of legacy key packages from the validation service
- [ ] Rename `GetIdentityUpdatesV2` in libxmtp back to `GetIdentityUpdates`
```
